services:
  vtt:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4444:4444"
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./server:/app/server
      - ./index.html:/app/index.html
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - vtt-data:/app/db
      - vtt-uploads:/app/server/uploads
    environment:
      - VITE_SERVER_PORT=4444
      - VITE_DEV_PORT=5173

volumes:
  vtt-data:
  vtt-uploads:
